### ISSUE TITLE
system freeze on D945GCLF2 w/Atom CPU

### ISSUE THREAD

**Issue by jiyunomegami** [crazii/SBEMU#65]
SBEMU would cause a system freeze when writing to the CORB buffer on my D945GCLF2 w/Atom CPU.
Everything appears to work properly if you use PIO in azx_single_send_cmd and azx_get_response.
I added an option /PIO1 to use PIO.
This might fix some of the "Dell Latitude" issues.
Please see the pull request #64

**Comment by volkertb** [comment]
Thanks for submitting a PR with this improvement!

A bit of a clueless question: when using PIO instead of CORB, doesn't that mean that the sound is streamed out through direct I/O as opposed to DMA? If so, doesn't that have implication for the DMA handling of the emulated Sound Blaster card? I would expect that with CORB, it would just be a batter of passing on the correct memory reference and have the HDA perform DMA on it (with the 8257-specific expects of DMA being trapped an emulated, but the actual direct memory access aspect of it still occurring on the HDA side of things).

But with PIO, wouldn't we need some kind of "pseudo-DMA", to read the RAM and stream it to the HDA device in the background somehow? Your PR only includes some small changes here and there, and nothing like this.

Or am I completely misunderstanding how this works?

Thanks in advance to anybody who can clarify this to me.

**Comment by jiyunomegami** [comment]
The PIO option only changes how commands are sent to the codecs.
DMA handling of audio data is unchanged.
Apparently, "platforms not suited for DMA command operations" exist such that you must use PIO to send commands.

From the HDA specification(1.):

> 3.4 Immediate Command Input and Output Registers
> The Immediate Command Output and Immediate Command Input registers are optional registers
> which provide a Programmed I/O (PIO) interface for sending verbs and receiving responses from
> codecs. **These registers can be implemented in platforms not suited for DMA command operations.**
> If implemented, these registers must not be used at the same time as the CORB and RIRB
> command/response mechanisms, as the operations will conflict. 

1) https://www.intel.com/content/dam/www/public/us/en/documents/product-specifications/high-definition-audio-specification.pdf

**Comment by crazii** [comment]
Yes, need detection (i.e. timeout? or need to conform if any status register indicates only PIO works) whether CORB/RIRB works, if not, then fallback to PIO mode.
In previous tests, almost all chipset supports CORB but a lot of them doesn't work with PIO, the original code of MPXPLAY uses PIO only but not working on tested chipsets, that's why PIO is removed. (the spec says it's "optional").
but it's true by the spec that there's a case only PIO works.

**Comment by crazii** [comment]
> Thanks for submitting a PR with this improvement!
> 
> A bit of a clueless question: when using PIO instead of CORB, doesn't that mean that the sound is streamed out through direct I/O as opposed to DMA? If so, doesn't that have implication for the DMA handling of the emulated Sound Blaster card? I would expect that with CORB, it would just be a batter of passing on the correct memory reference and have the HDA perform DMA on it (with the 8257-specific expects of DMA being trapped an emulated, but the actual direct memory access aspect of it still occurring on the HDA side of things).
> 
> But with PIO, wouldn't we need some kind of "pseudo-DMA", to read the RAM and stream it to the HDA device in the background somehow? Your PR only includes some small changes here and there, and nothing like this.
> 
> Or am I completely misunderstanding how this works?
> 
> Thanks in advance to anybody who can clarify this to me.

No, PIO mode is only for COMMANDS.
"These registers can be implemented in platforms not suited for DMA _command_ operations."

**Comment by volkertb** [comment]
Very insightful. Thank you both for clarifying.
