### ISSUE TITLE
SBEMU issues with FastDoom

### ISSUE THREAD

**Issue by viti95** [crazii/SBEMU#88]
There are some issues with FastDoom, mainly SB emulation is not working properly. FastDoom uses DOS32/A extender instead of DOS/4G. It's working fine on real hardware, so there is some kind of incompatibility.

Here is a message from @Baron-von-Riedesel in VOGONS to make it partially compatible:

"Well, I played a bit with Fastdoom and can say that it partially works with both SBEMU and VSBHDA. There are a few issues:

- hdpmi32i should be loaded with the -x option, since the DOS32A extender isn't happy if too much free memory is offered
- if Soundblaster FM music is enabled, a crash will happen. Soundblaster SFX works, though!
- It must be ensured that hdpmi is used as DPMI host for Fastdoom. I achieved this by entering "JEMMEX NOVCPI" before launching fastdoom.

I also compiled Fastdoom with Watcom v1.9, creating a HX binary instead of DOS32A - it works."

**Comment by crazii** [comment]
Novcpi is needed for some games and there's no good solution.
But the crash is a serious problem that should be fixed, thanks for the feedback!

**Comment by crazii** [comment]
I test the with the latest build of SBEMU and FastDOOM, and it fails with 'Error Initializing Music device: -1`, no crashes, I will try to fix the Adlib handling.

**Comment by hjnijlunsing** [comment]
When selecting no FM and Sound Blaster as FX (Both with direct and non-direct)  it fails with "Error setup Sound device: -1", thus SFX does not work on my machine

**Comment by crazii** [comment]
> When selecting no FM and Sound Blaster as FX (Both with direct and non-direct) it fails with "Error setup Sound device: -1", thus SFX does not work on my machine

did you run ```jemmex novcpi``` after sbemu? fastdoom/dos32a needs this to work.

**Comment by hjnijlunsing** [comment]
My bad, indeed that solves the FX...

**Comment by crazii** [comment]
I'm debugging it, and some information might help, since you are the owner of fast doom, it might be more easy that I ask you:  how many tasks are installed by ```TS_ScheduleTask``` when sound blaster SFX + sound blaster music are selected?
As I read the code of fastdoom, it seems only ```_MIDI_ServiceRoutine``` are used, besides ```I_TimerISR```/```I_TimerMS```.
Does any of those tasks calls any real mode code directly/indirectly?

Also I found an irrelevant problem: fast doom has no opl music on DOSBox-X, for default opl or nuked opl emulation, general midi / sound blaster midi works.  You can ignore it if DOSBox is not intended to be supported.

**Comment by crazii** [comment]
Never mind. I just found the in-compatibility problem, but currently there's no way to fix it in SBEMU or HDPMI, because HDPMI does what the DPMI spec requires. I modified the code of FastDoom a little bit so that it works with HDPMI/SBEMU, and I believe it also works as the original code (for the real SB HW). 

I'll create a PR tomorrow.

**Comment by viti95** [comment]
I'm really curious to see what's doing DOS32/A different. Sorry for not being able to provide more feedback/information, these days have been quite stressing for me. Thanks.

**Comment by crazii** [comment]
No problem. What I did is just switching to a pm stack. check this [PR](https://github.com/viti95/FastDoom/pull/178) for details.

**Comment by viti95** [comment]
I've been testing this on multiple PC's and it's working really good, so we can close this issue. Thanks!!
