### ISSUE TITLE
Thinkpad T41 compatibility

### ISSUE THREAD

**Issue by Torinde** [crazii/SBEMU#95]
The following issue was resolved at VSBHDA:
- https://github.com/Baron-von-Riedesel/VSBHDA/issues/4#issuecomment-1934590211
> Well, I checked the port 0x20 trapping with DEBUG. The I/O simulation for IN and OUT did modify parts of register AX that should have remained constant - both with QPIEMU.DLL and Qemm. So rmtrap.asm had a bug and has been fixed.

I don't know if SBEMU already handles that.

**Comment by crazii** [comment]
SBEMU should not have that problem, rmtrap.asm is an modified code for VSBHDA.  SBEMU doesn't have it. I didn't read the code but VSBHDA does rm trap in a different way I guess.

**Comment by crazii** [comment]
SBEMU traps rm ports and goes to PM, I guess VSBHDA optimized out the mode switches by handling the trap in rm?  That's why it permanently traps rm PIC ports while SBEMU only temporarily trap PIC for rm programs when raising the virtual SB IRQ to avoid unnecessary mode switches and thus improve performance.
